name: Setup
description: Sets up Node and Build SDK

inputs:
  node-version:
    description: "Specify Node version"
    required: false
    default: "22"

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org

    - name: Set NODE_VERSION env
      shell: bash
      run: echo "NODE_VERSION=$(node --version)" >> $GITHUB_ENV

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-${{ inputs.node-version }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-${{ inputs.node-version }}-modules-

    - name: Install Dependencies & Build
      run: yarn install --frozen-lockfile --ignore-engines
      shell: bash
