yarnPath: .yarn/releases/yarn-4.15.0.cjs
nodeLinker: node-modules
enableTelemetry: false

# Hardening + supply-chain
nmMode: hardlinks-global
enableHardenedMode: true
enableScripts: false
enableGlobalCache: true
npmMinimalAgeGate: 3d
npmPublishProvenance: true
