export const mockChannelQueryResponse = {
	channel: {
		id: '!members-VTb-DIRK8V2pHHguhdYktHnmOGCfRzphbD2BDcXjItE',
		type: 'messaging',
		cid: 'messaging:!members-VTb-DIRK8V2pHHguhdYktHnmOGCfRzphbD2BDcXjItE',
		last_message_at: '2023-11-14T12:39:29.396443Z',
		created_at: '2023-08-18T09:06:45.421888Z',
		updated_at: '2023-11-15T08:26:11.595394Z',
		created_by: {
			id: 'zitaszuperagetstreamio',
			role: 'admin',
			created_at: '2021-09-14T13:07:45.764353Z',
			updated_at: '2023-11-02T10:43:16.258959Z',
			last_active: '2022-07-15T07:08:03.807199Z',
			banned: false,
			online: false,
			first_name: 'Zita',
			staff_user: true,
			dashboard_user: true,
			name: 'Zita Szupera',
			email: 'zita.szupera@getstream.io',
			image: 'https://getstream.io/random_png/?id=little-wood-9\u0026name=little-wood-9',
			last_name: 'Szupera',
		},
		frozen: true,
		disabled: false,
		member_count: 2,
		config: {
			created_at: '2021-11-10T13:31:08.527632Z',
			updated_at: '2023-10-25T11:22:29.482779Z',
			name: 'messaging',
			typing_events: true,
			read_events: true,
			connect_events: true,
			search: true,
			reactions: true,
			replies: true,
			quotes: true,
			mutes: true,
			uploads: true,
			url_enrichment: true,
			custom_events: true,
			push_notifications: true,
			reminders: false,
			mark_messages_pending: false,
			message_retention: 'infinite',
			max_message_length: 5000,
			automod: 'AI',
			automod_behavior: 'flag',
			blocklist: 'profanity_en_2020_v1',
			blocklist_behavior: 'flag',
			automod_thresholds: {},
			commands: [
				{
					name: 'giphy',
					description: 'Post a random gif to the channel',
					args: '[text]',
					set: 'fun_set',
				},
				{
					name: 'ban',
					description: 'Ban a user',
					args: '[@username] [text]',
					set: 'moderation_set',
				},
				{
					name: 'mute',
					description: 'Mute a user',
					args: '[@username]',
					set: 'moderation_set',
				},
				{
					name: 'unmute',
					description: 'Unmute a user',
					args: '[@username]',
					set: 'moderation_set',
				},
				{
					name: 'unban',
					description: 'Unban a user',
					args: '[@username]',
					set: 'moderation_set',
				},
			],
		},
		cooldown: 30,
		own_capabilities: [
			'ban-channel-members',
			'connect-events',
			'delete-any-message',
			'delete-channel',
			'delete-own-message',
			'flag-message',
			'freeze-channel',
			'join-channel',
			'leave-channel',
			'mute-channel',
			'read-events',
			'search-messages',
			'send-custom-events',
			'send-typing-events',
			'set-channel-cooldown',
			'skip-slow-mode',
			'typing-events',
			'update-any-message',
			'update-channel',
			'update-own-message',
			'upload-file',
		],
		hidden: false,
		name: 'Edit channel2',
	},
	messages: [],
	pinned_messages: [],
	members: [
		{
			user_id: 'sara-angular-test',
			user: {
				id: 'sara-angular-test',
				role: 'user',
				created_at: '2023-06-27T10:13:12.796304Z',
				updated_at: '2023-11-03T09:48:35.748166Z',
				last_active: '2023-11-14T07:47:29.732473872Z',
				banned: false,
				online: false,
				name: 'Jack',
				email: '',
			},
			created_at: '2023-08-18T09:06:45.431978Z',
			updated_at: '2023-08-18T09:06:45.431978Z',
			banned: false,
			shadow_banned: false,
			role: 'member',
			channel_role: 'channel_member',
			notifications_muted: false,
		},
	],
	membership: {
		user: {
			id: 'zitaszuperagetstreamio',
			role: 'admin',
			created_at: '2021-09-14T13:07:45.764353Z',
			updated_at: '2023-11-02T10:43:16.258959Z',
			last_active: '2022-07-15T07:08:03.807199Z',
			banned: false,
			online: false,
			last_name: 'Szupera',
			first_name: 'Zita',
			staff_user: true,
			dashboard_user: true,
			name: 'Zita Szupera',
			email: 'zita.szupera@getstream.io',
			image: 'https://getstream.io/random_png/?id=little-wood-9\u0026name=little-wood-9',
		},
		created_at: '2023-08-18T09:06:45.431978Z',
		updated_at: '2023-08-18T09:06:45.431978Z',
		banned: false,
		shadow_banned: false,
		role: 'owner',
		channel_role: 'channel_member',
		notifications_muted: false,
	},
	duration: '3.22ms',
};
