export interface CustomAttachmentData {}
export interface CustomChannelData {}
export interface CustomCommandData {}
export interface CustomEventData {}
export interface CustomMemberData {}
export interface CustomMessageData {}
export interface CustomPollOptionData {}
export interface CustomPollData {}
export interface CustomReactionData {}
export interface CustomUserData {}
export interface CustomThreadData {}
export interface CustomMessageComposerData {}
