// @generated by protobuf-ts 2.7.0 with parameter long_type_string,generate_dependencies,client_generic,server_none
// @generated from protobuf file "chat/client_v2_rpc/rpc.proto" (package "stream.chat.client_v2_rpc", syntax proto3)
// tslint:disable
import { QueryChannelsResponse } from "./channel";
import { QueryChannelsRequest } from "./channel";
import { GetChannelResponse } from "./channel";
import { GetChannelRequest } from "./channel";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service stream.chat.client_v2_rpc.ClientRPC
 */
export const ClientRPC = new ServiceType("stream.chat.client_v2_rpc.ClientRPC", [
    { name: "GetChannel", localName: "getChannel$", options: {}, I: GetChannelRequest, O: GetChannelResponse },
    { name: "QueryChannels", options: {}, I: QueryChannelsRequest, O: QueryChannelsResponse }
]);
