// @generated by protobuf-ts 2.7.0 with parameter long_type_string,generate_dependencies,client_generic,server_none
// @generated from protobuf file "chat/v2/client_rpc/clientside.proto" (package "stream.chat.v2.client_rpc", syntax proto3)
// tslint:disable
import { QueryChannelResponse } from "./channel";
import { QueryChannelRequest } from "./channel";
import { GetChannelResponse } from "./channel";
import { GetChannelRequest } from "./channel";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service stream.chat.v2.client_rpc.ClientChatService
 */
export const ClientChatService = new ServiceType("stream.chat.v2.client_rpc.ClientChatService", [
    { name: "GetChannel", localName: "getChannel$", options: {}, I: GetChannelRequest, O: GetChannelResponse },
    { name: "QueryChannel", options: {}, I: QueryChannelRequest, O: QueryChannelResponse }
]);
